services:
  _defaults:
    public: true
    autowire: true

  huh.location.data_container.location_container:
    class: HeimrichHannot\LocationBundle\DataContainer\LocationContainer

  huh.location.data_container.location_archive_container:
    class: HeimrichHannot\LocationBundle\DataContainer\LocationArchiveContainer