services:
  _defaults:
    autowire: true
    autoconfigure: true

  HeimrichHannot\LocationBundle\:
    resource: '../../{DataContainer,ConfigElementType}/*'

  HeimrichHannot\LocationBundle\DataContainer\LocationContainer:
    public: true