<?php

namespace HeimrichHannot\LocationBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class HeimrichHannotLocationBundle extends Bundle
{
    public function getPath()
    {
        return \dirname(__DIR__);
    }

    protected function getContainerExtensionClass()
    {
        return parent::getContainerExtensionClass(); // TODO: Change the autogenerated stub
    }


}